---
# tasks file for wireshark
- name: Test for the existance of /usr/local/bin/wireshark
  stat: path=/usr/local/bin/wireshark
  register: wireshark_binary
- name: Download Wireshark dmg file
  get_url: url="{{ wireshark_url }}"
           dest="{{ downloads }}/{{ wireshark_dmg }}"
  when: wireshark_binary.stat.exists == False
- name: Mount Wireshark image
  command: hdiutil attach "{{ wireshark_dmg }}" chdir="{{ downloads }}"
  become: yes
  when: wireshark_binary.stat.exists == False
- name: Install Wireshark pkg
  command: installer -package "{{ mount_path }}/Wireshark {{ wireshark_version }}.pkg" -target /
  become: yes
  when: wireshark_binary.stat.exists == False
- name: Unmount Wireshark image
  command: hdiutil detach "{{ mount_path }}"
  become: yes
  when: wireshark_binary.stat.exists == False
