---
# tasks file for add-demouser-account
- name: Adding demouser account
  user: name='demouser'
    comment='demouser' 
    createhome=yes
    append=yes
    groups='adm,cdrom,sudo,dip,plugdev,lpadmin,sambashare'
    state=present
    password='$6$0uv2s1to$4jNYr75l5bq6YaLWBYorzj.h.eYhkhshofjreOvgOb6Pv5oJobcFc5VNcliOV345.cKY7T79W3y1wnqT1bmXc0'
    system=no
  become: True
# Hide the vagrant user while we are at it
- name: Configure vagrant as a system user in AccountsService
  replace: dest=/var/lib/AccountsService/users/vagrant regexp='^SystemAccount=false$' replace='SystemAccount=true'
  become: True
- name: Copy the demoserver binary to ~demouser/
  copy:
    dest: "/home/demouser/demoserver"
    src: "/data/demoserver"
    remote_src: True
    owner: "demouser"
    group: "demouser"
    mode: "0755"
  become: yes
# Edit the icons in the unity task bar
- name: Update the icons docked in the Unity Launcher
  shell: "cp /data/fix-launcher.sh /home/demouser/.fix-launcher.sh && mkdir -p /home/demouser/.config/autostart/ && cp /data/fix-launcher.desktop /home/demouser/.config/autostart/"
  become: yes
  become_user: demouser
  when: has_GUI == "yes"
# Tweak Ubuntus invasive privacy settings
- name: Security Settings - Do not remember files
  shell: "dbus-launch --exit-with-session gsettings set org.gnome.desktop.privacy remember-recent-files 'false'"
  become: yes
  become_user: demouser
  when: has_GUI == "yes"
- name: Security Settings - Do not search Internet
  shell: "dbus-launch --exit-with-session gsettings set com.canonical.Unity.Lenses remote-content-search 'none'"
  become: yes
  become_user: demouser
  when: has_GUI == "yes"
